%
% This file is part of TopoCell.
% 
% TopoCell is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version.
% 
% TopoCell is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License 
% along with TopoCell. If not, see <http://www.gnu.org/licenses/>.
%

function out = particlesData()

out = struct( ...
    'id', {}, ...
    'type', {}, ...
    'geoC_x', {}, ...
    'geoC_y', {}, ...
    'geoC_z', {}, ...
    'dist_geoCP_geoCC', {}, ...
    'dist_geoCP_memb', {}, ...
    'vol', {}, ...
    'int_avg', {}, ...
    'int_max', {}, ...
    'spher', {} ...
    );