function out = particlesData()

out = struct( ...
    'id', {}, ...
    'type', {}, ...
    'geoC_x', {}, ...
    'geoC_y', {}, ...
    'geoC_z', {}, ...
    'dist_geoCP_geoCC', {}, ...
    'dist_geoCP_memb', {}, ...
    'vol', {}, ...
    'int_avg', {}, ...
    'int_max', {}, ...
    'spher', {} ...
    );