function out = subjectsData()

out = struct( ...
    'group', {}, ... 
    'subject', {}, ...
    'particleMap', {struct( ...
        'id', {}, ...
        'name', {} ...
    )}, ...
    'cells', {struct( ...
        'id', {}, ...
        'vol', {}, ...
        'geoC_x', {}, ...
        'geoC_y', {}, ...
        'geoC_z', {}, ...
        'P_totint', {}, ...
        'P_vol', {}, ...
        'particles', particlesData() ...
    )} ...
);
